version: '3'
services:
  laravel:
    image: leejoneshane/laravel
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 5173:5173
    environment:
      APP_URL: http://localhost
      TZ: Asia/Taipei
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: webmaster@tc.meps.tp.edu.tw
      MAIL_FROM_NAME: 國語實小E化服務網
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: client_host=host.docker.internal
      MEILISEARCH_HOST: http://melisearch:7700
      MEILISEARCH_KEY: masterKey
      TPEDU_APP: 46
      TPEDU_SECRET: ksVxXGNhb3j9XCGZRUUMNdsMfriRHknB21aAvP51
      TPEDU_CALLBACK: https://www2.meps.tp.edu.tw/retrieve.asp
      TPEDU_TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImp0aSI6ImMwOTE5ZmQxYjA2ZmRlOTk5MDU1MjdlNWRmMTQ1YmUwNjc2NTU5Y2UxOTFiOWY1ZjdjMTBiODA2NmU0YWRmYzFmYTQ2OWMwYzAxNWE4ODU3In0.eyJhdWQiOiIxIiwianRpIjoiYzA5MTlmZDFiMDZmZGU5OTkwNTUyN2U1ZGYxNDViZTA2NzY1NTljZTE5MWI5ZjVmN2MxMGI4MDY2ZTRhZGZjMWZhNDY5YzBjMDE1YTg4NTciLCJpYXQiOjE2MjQwMTk1MzgsIm5iZiI6MTYyNDAxOTUzOCwiZXhwIjoxNjU1NTU1NTM4LCJzdWIiOiIxIiwic2NvcGVzIjpbInByb2ZpbGUiLCJzY2hvb2wiLCJzY2hvb2xBZG1pbiJdfQ.VwxkElum3-pt_wfz7f6b19RtAh1rZ5ztJJvBEWFDwbprsaSDgDK556kj5FkYXj8hNzPJpvncGdmboSQZuzOB1JFRtNg-ihgi7uR4451IyR4dEUihTaVwAMHOHuZK9fEfUq82U-_3mnP4qX9Wvr6fooNOF85Bz-4nXDqXq3vcNZOqILk9ASa89bTV4QiIA9TkD0zA7AL6Sjo3hD9hKTJ2sDBlTr7VD6BN_J1YJh7NXeYxOYnAsnke3ntq5QLrq2SfADKRlTyz2OglmYH5fy-ITepWE0EGp6URayqGNLnHoWDgKCzpq6alNL90iS0MsaBo4a3bWEURvbqOc0WsCZr7ZJomU6NeXxKBvomjMFMDQ5GduMIH9Ja1UzNzjb13qJt74_SzVdIC-PaP-F0wU2GM4cmBCLaqHRs5XLwV2cIAgUO16zjMnc2wbmcbdzClwqjVTcUqv_6kWjxkc2LFFSfuNKD1yyZhnI5tya5nw8phkIFKnN3Y08MuyVoEprwc-pcPRZRIKjcEth-7DnTpkvHccJwu-sWSVGU9bNsjaKCCJVjA0se5I_8xjpivrMh0bJb7AlML1kno8RUZj-JOBybC3jVe0d64SQbjxX65ondRMeJmyNfxdw8DHLhw36L9UfgzJVWQXMoHQ698jOTX8vp1tC1VQPdvBhj86oSJxSITS-M
      SCHOOL: meps
      AD_HOST: ad06
      AD_PASS: ad_password
      AD_BASE_DN: DC=meps,DC=tp,DC=edu,DC=tw
      AD_USERS_DN: CN=users,DC=meps,DC=tp,DC=edu,DC=tw
      AD_CA_FILE: /var/www/html/storage/ad.cer
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailhog
      
  redis:
    image: redis
    networks:
      - backend
      
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_ENV: production
    volumes:
      - ./:/meili_data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - backend
      
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    networks:
      - backend

networks:
  backend:
    driver: bridge