version: '3'
services:
  laravel:
    image: leejoneshane/laravel
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
    environment:
      APP_URL: http://localhost
      TZ: Asia/Taipei
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: webmaster@tc.meps.tp.edu.tw
      MAIL_FROM_NAME: 國語實小E化服務網
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: database
      QUEUE_FAILED_DRIVER: database-uuids
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: client_host=host.docker.internal
      MEILISEARCH_HOST: http://melisearch:7700
      MEILISEARCH_KEY: masterKey
      TPEDU_APP: oauth_id
      TPEDU_SECRET: secret
      TPEDU_CALLBACK: https://your.website/auth
      TPEDU_TOKEN: school_admin_token
      SCHOOL: xxps
      AD_HOST: ad06
      AD_PASS: ad_password
      AD_BASE_DN: DC=meps,DC=tp,DC=edu,DC=tw
      AD_USERS_DN: CN=users,DC=meps,DC=tp,DC=edu,DC=tw
      AD_CA_FILE: /var/www/html/storage/ad.cer
      GOOGLE_DOMAIN: gsuite.domain
      GOOGLE_AUTH_CONFIG: /var/www/html/storage/google.json
      GOOGLE_ADMIN: admin@gsuite.domain
      GOOGLE_CALENDAR_OWNER: calendar@gsuite.domain
      GOOGLE_TEACHER_ORGUNIT: /
      GOOGLE_STUDENT_ORGUNIT: /students
      FACEBOOK_CLIENT_ID: fb
      FACEBOOK_CLIENT_SECRET: secret
      GOOGLE_CLIENT_ID: google
      GOOGLE_CLIENT_SECRET: secret
      YAHOO_CLIENT_ID: google
      YAHOO_CLIENT_SECRET: secret
      LINE_CLIENT_ID: google
      LINE_CLIENT_SECRET: secret
      VITE_PUSHER_APP_ID: eschool
      VITE_PUSHER_APP_SECRET: meps_eschool_websocket
      VITE_PUSHER_APP_KEY: websocket_key
      VITE_PUSHER_HOST: ws.meps.tp.edu.tw
      VITE_PUSHER_PORT: 443
      VITE_PUSHER_SCHEME: https
    volumes:
      - ./html/:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql
      - redis
      - mailhog
      
  redis:
    image: redis
    networks:
      - backend
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - backend
      
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    networks:
      - backend

  soketi:
    image: quay.io/soketi/soketi
    environment:
      SOKETI_DEBUG: 1
      SOKETI_METRICS_SERVER_PORT: 9601
    ports:
      - 6001:6001
      - 9601:9601
    networks:
      - backend

networks:
  backend:
    driver: bridge