version: '3'
services:
  laravel:
    image: leejoneshane/laravel
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
      - 5173:5173
    environment:
      APP_URL: http://localhost
      TZ: Asia/Taipei
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_USERNAME: null
      MAIL_PASSWORD: null
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: webmaster@tc.meps.tp.edu.tw
      MAIL_FROM_NAME: 國語實小E化服務網
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: null
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: 123456
      XDEBUG_MODE: 'off'
      XDEBUG_CONFIG: client_host=host.docker.internal
      MEILISEARCH_HOST: http://melisearch:7700
      MEILISEARCH_KEY: masterKey
      TPEDU_APP: oauth_id
      TPEDU_SECRET: secret
      TPEDU_CALLBACK: https://your.website/auth
      TPEDU_TOKEN: school_admin_token
      SCHOOL: xxps
      AD_HOST: ad06
      AD_PASS: ad_password
      AD_BASE_DN: DC=meps,DC=tp,DC=edu,DC=tw
      AD_USERS_DN: CN=users,DC=meps,DC=tp,DC=edu,DC=tw
      AD_CA_FILE: /var/www/html/storage/ad.cer
    volumes:
      - ./:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql
      - redis
      - meilisearch
      - mailhog
      
  redis:
    image: redis
    networks:
      - backend
      
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - 7700:7700
    environment:
      MEILI_MASTER_KEY: masterKey
      MEILI_ENV: production
    volumes:
      - ./:/meili_data
    networks:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider",  "http://localhost:7700/health"]
      retries: 3
      timeout: 5s
      
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
    networks:
      - backend
      
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: laravel
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    ports:
      - 8080:80
    networks:
      - backend

networks:
  backend:
    driver: bridge